import { library } from "@fortawesome/fontawesome-svg-core"
import {
  faAddressCard,
  faBriefcase,
  faBuilding,
  faBullseye,
  faCaretDown,
  faCaretRight,
  faCheck,
  faCircleCheck,
  faCity,
  faDatabase,
  faFileLines,
  faListCheck,
  faMap,
  faPenToSquare,
  faPlus,
  faRightFromBracket,
  faRotateRight,
  faTableList,
  faTrash,
  faUser,
  faUsers,
  faXmark,
} from "@fortawesome/free-solid-svg-icons"
library.add([
  faAddressCard,
  faBriefcase,
  faBuilding,
  faBullseye,
  faCaretDown,
  faCaretRight,
  faCheck,
  faCircleCheck,
  faCity,
  faDatabase,
  faFileLines,
  faListCheck,
  faMap,
  faPenToSquare,
  faPlus,
  faRightFromBracket,
  faRotateRight,
  faTableList,
  faTrash,
  faUser,
  faUsers,
  faXmark,
])

export { library }
